name: medcorder_audio
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

flutter:
  plugin:
    androidPackage: co.medcorder.medcorderaudio
    pluginClass: MedcorderAudioPlugin

dependencies:
  flutter:
    sdk: flutter
