name: medcorder_audio
description: Flutter audio record/play plugin.
version: 0.0.1
author: Dzmirty Kryvalapau <dimmetrius@gmail.com>
homepage: https://github.com/evrone/flutter_audio

flutter:
  plugin:
    androidPackage: co.medcorder.medcorderaudio
    pluginClass: MedcorderAudioPlugin

dependencies:
  flutter:
    sdk: flutter
